Repository adopted-ember-addons/ember-paper, pull requests merged in 2024-10, with the labels that each got.

#1255 update lint-to-the-future
  package-lock.json
  package.json
Labels: internal

#1257 build(deps): updates to `ember-css-transitions@^3.1.0`.
  package-lock.json
  package.json
Labels: enhancement

#1260 build(deps): upgrades to `ember-css-transitions@^4.4.1`.
  package-lock.json
  package.json
Labels: dependencies

#1284 make sure ember-cli-deprecation-workflow config is up to date
  package.json
  pnpm-lock.yaml
  tests/dummy/config/deprecation-workflow.js
Labels: internal

#1285 chore: remove no-implicit-this lint errors
  addon/components/paper-button.hbs
  addon/components/paper-card-media.hbs
  addon/components/paper-card-title-media.hbs
  addon/components/paper-checkbox.hbs
  addon/components/paper-contact-chips/template.hbs
  addon/components/paper-dialog.hbs
  addon/components/paper-form.hbs
  addon/components/paper-icon.hbs
  addon/components/paper-input.hbs
  addon/components/paper-input.js
  addon/components/paper-item.hbs
  addon/components/paper-optgroup.hbs
  addon/components/paper-progress-circular.hbs
  addon/components/paper-progress-linear.hbs
  addon/components/paper-radio-base.hbs
  addon/components/paper-radio-group-label.hbs
  addon/components/paper-radio-group.hbs
  addon/components/paper-sidenav-toggle.hbs
  addon/components/paper-sidenav.hbs
  addon/components/paper-speed-dial-actions.hbs
  addon/components/paper-switch.hbs
  addon/components/paper-tab.hbs
  addon/components/paper-tabs.hbs
  addon/components/paper-toast.hbs
  addon/components/paper-toaster.hbs
  addon/components/paper-tooltip.hbs
  tests/dummy/app/templates/application.hbs
  tests/dummy/app/templates/components/doc-content.hbs
  tests/dummy/app/templates/components/example-item.hbs
  tests/dummy/app/templates/components/menu-item.hbs
  tests/dummy/app/templates/components/not-found.hbs
  tests/dummy/app/templates/components/page-toolbar.hbs
  tests/dummy/app/templates/components/paper-api.hbs
  tests/dummy/app/templates/components/submenu-item.hbs
  tests/dummy/app/templates/demo/autocomplete.hbs
  tests/dummy/app/templates/demo/checkbox.hbs
  tests/dummy/app/templates/demo/chips.hbs
  tests/dummy/app/templates/demo/dialog.hbs
  tests/dummy/app/templates/demo/divider.hbs
  tests/dummy/app/templates/demo/grid-list.hbs
  tests/dummy/app/templates/demo/input.hbs
  tests/dummy/app/templates/demo/list.hbs
  tests/dummy/app/templates/demo/menu.hbs
  tests/dummy/app/templates/demo/progress-circular.hbs
  tests/dummy/app/templates/demo/progress-linear.hbs
  tests/dummy/app/templates/demo/radio.hbs
  tests/dummy/app/templates/demo/select.hbs
  tests/dummy/app/templates/demo/sidenav.hbs
  tests/dummy/app/templates/demo/slider.hbs
  tests/dummy/app/templates/demo/speed-dial.hbs
  tests/dummy/app/templates/demo/switch.hbs
  tests/dummy/app/templates/demo/tabs.hbs
  tests/dummy/app/templates/demo/toast.hbs
  tests/dummy/app/templates/demo/tooltip.hbs
  tests/dummy/app/templates/forms.hbs
  tests/dummy/app/templates/layout/child-alignment.hbs
  tests/dummy/app/templates/layout/introduction.hbs
  tests/dummy/app/templates/theme.hbs
Labels: internal

#1274 docs: migrates url references to adopted-ember-addons.
  README.md
  addon/components/paper-menu/content/component.js
  addon/components/paper-select/ebd-content/component.js
  addon/utils/ebd-get-parent.js
  package.json
  tests/dummy/app/index.html
  tests/dummy/app/templates/addons.hbs
  tests/dummy/app/templates/components/page-toolbar.hbs
  tests/dummy/app/templates/cookbook.hbs
  tests/dummy/app/templates/index.hbs
Labels: internal
